### ISSUE TITLE
Feature idea: Trace barrier

### ISSUE THREAD

**Issue by lukego** [raptorjit/raptorjit#115]
Problem: Traces in large programs often span far and wide from one side of the codebase to the other. This can make the generated code difficult to understand and predict. It can also allow blacklistings (#100) to propagate a long way so that an obscure JIT abort can become contagious and take down the performance of a whole process.

Proposed solution: Create a `jit.barrier()` function that forces the current trace to end (when executed during recording) and then allows a new trace to begin immediately afterwards. This operation could then be used judiciously by application developers to define boundaries between different parts of their system so that traces can include code in subsystem A or B but not both.

Implementation strategy: I see two main options, both fairly simple. The first would be for `jit.barrier()` to emit a guard that always fails. This would force a trace exit. If the exit were taken frequently then a new _side trace_ would be spawned. The second would be for `jit.barrier()` to trigger a "trace stitch" (#114) that completes the current trace before the barrier and then immediately starts recording a new one after the barrier.

The trace stitching approach seems the most appealing off hand. This way subsystems A and B will have separate root traces. If side traces are used then the heuristic decisions made while tracing subsystem A could still affect subsystem B too.

Could also be that a stitch-based`jit.barrier()` could be implemented as a one-liner in Lua i.e. simply as a call to a cheap library function that will make the JIT stitch a new trace and waste as little time as possible in between.

**Comment by afgbloch** [comment]
The idea is interesting,

I don't really see how the always falling guard would work, would it even be possible  to record such a trace ? or would it be a special case in the recording code ?
I think the stitching approach would not be too difficult to implement. Also it would make the "second" trace be recorded immediately instead of when the side exit would became hot. 

Also I don't really how all this would be useful for blacklistings. If a blacklisting in subsystem B affect  subsystem A it means that it is on the "hotpath" otherwise other traces local to subsystem A should be generated no ? Maybe the issues is more, how easy it is to blacklist a part of a code because of "weak" abort ?

**Comment by lukego** [comment]
@afgbloch I agree that the "always failing guard" has some implementation complexities, and it is likely not worth working them out because the trace stitching approach seems nicer.

The trouble with blacklistings is that they propagate backwards through the code base. Function A is blacklisted for having an NYI, function B is blacklisted for calling function A, function C is blacklisted for calling function B, etc. The barriers would potentially provide some containment i.e. once you reach a barrier your trace is "safe" and not at risk of continuing until it reaches an NYI/IFUNC/ILOOP.
