### ISSUE TITLE
Should I be able to compile Lua libraries against RaptorJIT?

### ISSUE THREAD

**Issue by presidentbeef** [raptorjit/raptorjit#207]
I have a [language implementation](https://github.com/presidentbeef/brat) that compiles to Lua and runs on LuaJIT.

For fun, I have tried (a few times) to naively replace LuaJIT with RaptorJIT to see what happens, but I get stuck on Lua libraries that use the C API. I basically point everything to RaptorJIT's libs, etc. when building the libraries, but I end up with these kinds of errors:

```
raptorjit: error loading module 'lfs' from file '/home/justin/work/brat/lib/lfs.so':
	/home/justin/work/brat/lib/lfs.so: undefined symbol: lua_gettop
stack traceback:
	[C]: at 0x004549b0
	[C]: in function 'require'
	/home/justin/work/brat/bin/brat:13: in main chunk
	[C]: at 0x00403140
```
(Here it's luafilesystem failing).
I've also tried just building something directly with RaptorJIT, like the [lpty](http://tset.de/lpty/index.html) library, with similar results:
```
RaptorJIT 1.0.0 -- http://github.com/raptorjit/raptorjit
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> require 'lpty'
error loading module 'lpty' from file './lpty.so':
	./lpty.so: undefined symbol: lua_gettop
stack traceback:
	[C]: at 0x004549b0
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: at 0x00403140
```

If I compile against regular Lua or LuaJIT, it works fine:
```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> require 'lpty'
> 
```

```
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> require 'lpty'
> 
```
I'm sure I'm just missing something silly, but I've been banging my head against this for a while.

Thanks!

**Comment by lukego** [comment]
Thanks for the report @presidentbeef. I'll take a look. I have actually never used the Lua C API - only the FFI - and so it's possible that something basic in the build is broken.

btw: You might be interested in my tutorial video on [How LuaJIT and RaptorJIT compile function calls](https://www.youtube.com/watch?v=swA9xFhjnGc) that tries to make the case for preferring the FFI to the C API. TLDR it's because FFI calls can be JIT'd and C-API calls can't.

**Comment by lukego** [comment]
Can you please check whether #209 fixes this problem? (It does for me when testing with lpty.)

The issue seems to be the Makefile missing the `-Wl,-E` flag to make GCC ensure that RaptorJIT's symbols are visible to loaded object code. Googling I came upon a similar issue at https://github.com/zdevito/terra/issues/6.

**Comment by presidentbeef** [comment]
Hi @lukego,

Thank you very much for the quick reply. #209 does fix the issue!

> btw: You might be interested in my tutorial video on How LuaJIT and RaptorJIT compile function calls that tries to make the case for preferring the FFI to the C API. TLDR it's because FFI calls can be JIT'd and C-API calls can't.

I use FFI myself if I have to interact with C, but I also like to rely on existing libraries :)

**Comment by lukego** [comment]
Thanks for confirming that @presidentbeef. I've added a basic test case on #212 that downloads `lpty`  and builds it with LuaJIT and links the result with RaptorJIT. This could be extended in the future to also test e.g. builds with Lua 5.1/5.2/5.3.

> I use FFI myself if I have to interact with C, but I also like to rely on existing libraries :)

Good idea. I am spoiled because [ljsyscall](https://github.com/justincormack/ljsyscall) usually does everything that I need so I'm not used to looking in LuaRocks etc.
